### ISSUE TITLE
issue when installing

### ISSUE THREAD

**Issue by amine-sakka** [thevpc/nuts#29]
$ nuts install pnote 
**command return error and show exception :**
### 
Exception in thread "main" java.lang.NoClassDefFoundError: net/thevpc/nuts/NutsActionSupportCondition
	at net.thevpc.pnote.PangaeaNoteMain.onInstallApplication(PangaeaNoteMain.java:51)
	at net.thevpc.nuts.NutsApplications.runApplication(NutsApplications.java:172)
	at net.thevpc.nuts.NutsApplication.run(NutsApplication.java:199)
	at net.thevpc.nuts.NutsApplication.run(NutsApplication.java:186)
	at net.thevpc.nuts.NutsApplications.runApplicationAndExit(NutsApplications.java:73)
	at net.thevpc.nuts.NutsApplication.runAndExit(NutsApplication.java:175)
	at net.thevpc.pnote.PangaeaNoteMain.main(PangaeaNoteMain.java:24)
Caused by: java.lang.ClassNotFoundException: net.thevpc.nuts.NutsActionSupportCondition
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 7 more

**Comment by thevpc** [comment]
fixed
