### ISSUE TITLE
[0.8.3.0] Error typing 'nuts search'

### ISSUE THREAD

**Issue by thevpc** [thevpc/nuts#31]
Error typing
'nuts search'

Caused by: java.lang.IllegalStateException: unable to cast object to array{"maven.compiler.target":"1.8", "nuts.categories":"/Settings/PackageManager/Nuts", "conditional-dependencies":"<conditional-dependencies>\n                <dependency>\n                    <groupId>org.fusesource.jansi</groupId>\n                    <artifactId>jansi</artifactId>\n                    <os>windows</os>\n                </dependency>\n                <dependency>\n                    <groupId>com.github.vatbub</groupId>\n                    <artifactId>mslinks</artifactId>\n                    <os>windows</os>\n                </dependency>\n            </conditional-dependencies>", "maven.compiler.source":"1.8", "nuts-runtime":"true", "dependencies.org.fusesource.jansi:jansi.os":"windows", "dependencies.com.github.vatbub:mslinks.os":"windows", "project.build.sourceEncoding":"UTF-8", "nuts.icons":"classpath://net/thevpc/nuts/runtime/nuts.svg\n            classpath://net/thevpc/nuts/runtime/nuts.png\n            classpath://net/thevpc/nuts/runtime/nuts.ico", "nuts.repositories":"~/.m2/repository\n            https://repo.maven.apache.org/maven2/", "github.global.server":"github"}
        at net.thevpc.nuts.runtime.core.format.elem.AbstractNutsElement.asArray(AbstractNutsElement.java:70)
        at net.thevpc.nuts.runtime.core.format.elem.mappers.NutsElementMapperCollection.createObject(NutsElementMapperCollection.java:61)
        at net.thevpc.nuts.runtime.core.format.elem.mappers.NutsElementMapperCollection.createObject(NutsElementMapperCollection.java:18)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.createObject(DefaultNutsElementFactoryService.java:286)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.createObject(DefaultNutsElementFactoryService.java:291)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryContext.elementToObject(DefaultNutsElementFactoryContext.java:104)
        at net.thevpc.nuts.runtime.core.format.elem.mappers.NutsElementMapperObjReflect.createObject(NutsElementMapperObjReflect.java:68)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.createObject(DefaultNutsElementFactoryService.java:286)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.defaultCreateObject(DefaultNutsElementFactoryService.java:296)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryContext.defaultElementToObject(DefaultNutsElementFactoryContext.java:114)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryContext.defaultElementToObject(DefaultNutsElementFactoryContext.java:98)
        at net.thevpc.nuts.runtime.core.format.elem.mappers.NutsElementMapperNutsDescriptor.createObject(NutsElementMapperNutsDescriptor.java:29)
        at net.thevpc.nuts.runtime.core.format.elem.mappers.NutsElementMapperNutsDescriptor.createObject(NutsElementMapperNutsDescriptor.java:11)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.createObject(DefaultNutsElementFactoryService.java:286)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryService.createObject(DefaultNutsElementFactoryService.java:291)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFactoryContext.elementToObject(DefaultNutsElementFactoryContext.java:104)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFormat.elementToObject(DefaultNutsElementFormat.java:280)
        at net.thevpc.nuts.runtime.core.format.elem.DefaultNutsElementFormat.parse(DefaultNutsElementFormat.java:169)
        at net.thevpc.nuts.runtime.core.parser.DefaultNutsDescriptorParser.parse(DefaultNutsDescriptorParser.java:116)
        at net.thevpc.nuts.runtime.core.parser.DefaultNutsDescriptorParser.parse(DefaultNutsDescriptorParser.java:52)
        ... 21 more

**Comment by thevpc** [comment]
This error is about using an old workspace format. So It wont happen if you create a new one. Will close the issue.
